import type { Batch } from "@/types/batch"

export const mockBatches: Batch[] = [
  {
    id: "WTC-001",
    company: "Forest Timber Co.",
    product: "Oak Wood Logs",
    quantity: 100,
    status: "delivered",
    blockchain: "Hyperledger",
    createdAt: "2024-01-10",
    lastUpdated: "2024-01-25",
    origin: "Oregon Forest, USA",
    destination: "Portland Lumber Mill, OR",
    transactionHash: "0x1a2b3c4d5e6f7890abcdef1234567890abcdef12",
    supplyChainStage: "finished-product",
    currentStageCompany: "Craftsman Furniture",
    leadTimeHours: 360,
    riskLevel: "low",
    chainProgression: [
      {
        company: "Forest Timber Co.",
        stage: "raw-material",
        blockchain: "Hyperledger",
        location: "Oregon Forest, USA",
        completedAt: "2024-01-12",
        transactionHash: "0x1a2b3c4d5e6f7890abcdef1234567890abcdef12",
        status: "completed",
      },
      {
        company: "Portland Lumber Mill",
        stage: "processing",
        blockchain: "Ethereum",
        location: "Portland, OR",
        completedAt: "2024-01-18",
        transactionHash: "0x2b3c4d5e6f7890abcdef1234567890abcdef1234",
        status: "completed",
      },
      {
        company: "Craftsman Furniture",
        stage: "manufacturing",
        blockchain: "Polygon",
        location: "Seattle, WA",
        completedAt: "2024-01-25",
        transactionHash: "0x3c4d5e6f7890abcdef1234567890abcdef123456",
        status: "completed",
      },
    ],
  },
  {
    id: "WTC-002",
    company: "Forest Timber Co.",
    product: "Maple Wood Logs",
    quantity: 150,
    status: "in-transit",
    blockchain: "Hyperledger",
    createdAt: "2024-01-15",
    lastUpdated: "2024-01-22",
    origin: "Vermont Forest, USA",
    destination: "Portland Lumber Mill, OR",
    transactionHash: "0x4d5e6f7890abcdef1234567890abcdef12345678",
    supplyChainStage: "processing",
    currentStageCompany: "Portland Lumber Mill",
    leadTimeHours: 168,
    riskLevel: "medium",
    chainProgression: [
      {
        company: "Forest Timber Co.",
        stage: "raw-material",
        blockchain: "Hyperledger",
        location: "Vermont Forest, USA",
        completedAt: "2024-01-17",
        transactionHash: "0x4d5e6f7890abcdef1234567890abcdef12345678",
        status: "completed",
      },
      {
        company: "Portland Lumber Mill",
        stage: "processing",
        blockchain: "Ethereum",
        location: "Portland, OR",
        status: "in-progress",
      },
      {
        company: "Craftsman Furniture",
        stage: "manufacturing",
        blockchain: "Polygon",
        location: "Seattle, WA",
        status: "pending",
      },
    ],
  },
  {
    id: "WTC-003",
    company: "Forest Timber Co.",
    product: "Cherry Wood Logs",
    quantity: 80,
    status: "verified",
    blockchain: "Hyperledger",
    createdAt: "2024-01-08",
    lastUpdated: "2024-01-28",
    origin: "Michigan Forest, USA",
    destination: "Portland Lumber Mill, OR",
    transactionHash: "0x5e6f7890abcdef1234567890abcdef123456789a",
    supplyChainStage: "finished-product",
    currentStageCompany: "Craftsman Furniture",
    leadTimeHours: 480,
    riskLevel: "low",
    chainProgression: [
      {
        company: "Forest Timber Co.",
        stage: "raw-material",
        blockchain: "Hyperledger",
        location: "Michigan Forest, USA",
        completedAt: "2024-01-10",
        transactionHash: "0x5e6f7890abcdef1234567890abcdef123456789a",
        status: "completed",
      },
      {
        company: "Portland Lumber Mill",
        stage: "processing",
        blockchain: "Ethereum",
        location: "Portland, OR",
        completedAt: "2024-01-20",
        transactionHash: "0x6f7890abcdef1234567890abcdef123456789abc",
        status: "completed",
      },
      {
        company: "Craftsman Furniture",
        stage: "manufacturing",
        blockchain: "Polygon",
        location: "Seattle, WA",
        completedAt: "2024-01-28",
        transactionHash: "0x7890abcdef1234567890abcdef123456789abcde",
        status: "completed",
      },
    ],
  },
  {
    id: "WTC-004",
    company: "Forest Timber Co.",
    product: "Walnut Wood Logs",
    quantity: 60,
    status: "pending",
    blockchain: "Hyperledger",
    createdAt: "2024-01-20",
    lastUpdated: "2024-01-20",
    origin: "California Forest, USA",
    destination: "Portland Lumber Mill, OR",
    supplyChainStage: "raw-material",
    currentStageCompany: "Forest Timber Co.",
    leadTimeHours: 0,
    riskLevel: "high",
    chainProgression: [
      {
        company: "Forest Timber Co.",
        stage: "raw-material",
        blockchain: "Hyperledger",
        location: "California Forest, USA",
        status: "in-progress",
      },
      {
        company: "Portland Lumber Mill",
        stage: "processing",
        blockchain: "Ethereum",
        location: "Portland, OR",
        status: "pending",
      },
      {
        company: "Craftsman Furniture",
        stage: "manufacturing",
        blockchain: "Polygon",
        location: "Seattle, WA",
        status: "pending",
      },
    ],
  },
  {
    id: "WTC-005",
    company: "Forest Timber Co.",
    product: "Pine Wood Logs",
    quantity: 200,
    status: "in-transit",
    blockchain: "Hyperledger",
    createdAt: "2024-01-12",
    lastUpdated: "2024-01-24",
    origin: "Washington Forest, USA",
    destination: "Portland Lumber Mill, OR",
    transactionHash: "0x890abcdef1234567890abcdef123456789abcdef",
    supplyChainStage: "manufacturing",
    currentStageCompany: "Craftsman Furniture",
    leadTimeHours: 288,
    riskLevel: "medium",
    chainProgression: [
      {
        company: "Forest Timber Co.",
        stage: "raw-material",
        blockchain: "Hyperledger",
        location: "Washington Forest, USA",
        completedAt: "2024-01-14",
        transactionHash: "0x890abcdef1234567890abcdef123456789abcdef",
        status: "completed",
      },
      {
        company: "Portland Lumber Mill",
        stage: "processing",
        blockchain: "Ethereum",
        location: "Portland, OR",
        completedAt: "2024-01-21",
        transactionHash: "0x90abcdef1234567890abcdef123456789abcdef1",
        status: "completed",
      },
      {
        company: "Craftsman Furniture",
        stage: "manufacturing",
        blockchain: "Polygon",
        location: "Seattle, WA",
        status: "in-progress",
      },
    ],
  },
]
