// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ILayerZeroEndpointV2$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ILayerZeroEndpointV2";
  readonly sourceName: "contracts/lz/ILayerZeroEndpointV2.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"oapp","type":"address"}],"name":"getSendLibrary","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"components":[{"internalType":"uint32","name":"dstEid","type":"uint32"},{"internalType":"bytes32","name":"receiver","type":"bytes32"},{"internalType":"bytes","name":"message","type":"bytes"},{"internalType":"bytes","name":"options","type":"bytes"},{"internalType":"address","name":"payInLzToken","type":"address"}],"internalType":"struct LZTypes.MessagingParams","name":"params","type":"tuple"},{"internalType":"address","name":"refundAddress","type":"address"}],"name":"send","outputs":[{"components":[{"internalType":"bytes32","name":"guid","type":"bytes32"},{"internalType":"uint64","name":"nonce","type":"uint64"}],"internalType":"struct LZTypes.MessagingReceipt","name":"","type":"tuple"}],"stateMutability":"payable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/lz/ILayerZeroEndpointV2.sol";
  readonly buildInfoId: "solc-0_8_24-4b1b45a0ae404438a2ac451d0484d0761e82f60e";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ILayerZeroEndpointV2"]: ILayerZeroEndpointV2$Type;
    ["contracts/lz/ILayerZeroEndpointV2.sol:ILayerZeroEndpointV2"]: ILayerZeroEndpointV2$Type;
  }
}