// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface LZTypes$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "LZTypes";
  readonly sourceName: "contracts/lz/LZTypes.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220db0a107967faef075cad07a326d82bc9db27ad523e9d0951c8bd34e4ce3a9c6064736f6c63430008180033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220db0a107967faef075cad07a326d82bc9db27ad523e9d0951c8bd34e4ce3a9c6064736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/lz/LZTypes.sol";
  readonly buildInfoId: "solc-0_8_24-4b1b45a0ae404438a2ac451d0484d0761e82f60e";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["LZTypes"]: LZTypes$Type;
    ["contracts/lz/LZTypes.sol:LZTypes"]: LZTypes$Type;
  }
}