// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ILayerZeroReceiverV2$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ILayerZeroReceiverV2";
  readonly sourceName: "contracts/lz/ILayerZeroReceiverV2.sol";
  readonly abi: [{"inputs":[{"components":[{"internalType":"uint32","name":"srcEid","type":"uint32"},{"internalType":"bytes32","name":"sender","type":"bytes32"},{"internalType":"uint64","name":"nonce","type":"uint64"}],"internalType":"struct LZTypes.Origin","name":"origin","type":"tuple"},{"internalType":"bytes32","name":"guid","type":"bytes32"},{"internalType":"bytes","name":"message","type":"bytes"},{"internalType":"address","name":"executor","type":"address"},{"internalType":"bytes","name":"extraData","type":"bytes"}],"name":"lzReceive","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/lz/ILayerZeroReceiverV2.sol";
  readonly buildInfoId: "solc-0_8_24-4b1b45a0ae404438a2ac451d0484d0761e82f60e";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ILayerZeroReceiverV2"]: ILayerZeroReceiverV2$Type;
    ["contracts/lz/ILayerZeroReceiverV2.sol:ILayerZeroReceiverV2"]: ILayerZeroReceiverV2$Type;
  }
}